-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 7192665e31cea6ace58a71e086c7248d7e5610c2
    hooks:
    -   id: autopep8-wrapper
        exclude: dfuse/.*
    -   id: check-added-large-files
        exclude: dfuse/.*
    -   id: check-case-conflict
        exclude: dfuse/.*
    -   id: check-docstring-first
        exclude: dfuse/.*
    -   id: check-json
        exclude: dfuse/.*
    -   id: check-merge-conflict
        exclude: dfuse/.*
    -   id: check-xml
        exclude: dfuse/.*
    -   id: check-yaml
        exclude: dfuse/.*
    -   id: debug-statements
        exclude: dfuse/.*
    -   id: detect-private-key
        exclude: dfuse/.*
    -   id: end-of-file-fixer
        exclude: dfuse/.*
    -   id: flake8
        exclude: dfuse/.*
    -   id: requirements-txt-fixer
        exclude: dfuse/.*
-   repo: git://github.com/asottile/reorder_python_imports
    sha: ab609b9b982729dfc287b4e75963c0c4de254a31
    hooks:
    -   id: reorder-python-imports
        exclude: dfuse/.*
